export default {
    /* ==================== Stylistic Rules ==================== */

    'stylistic/indent': ['error', 4],
    'stylistic/quotes': ['error', 'single', { avoidEscape: false, allowTemplateLiterals: true }],
    'stylistic/semi': ['error', 'always', { omitLastInOneLineBlock: false }],
    'stylistic/comma-dangle': ['error', 'always-multiline'],
    'stylistic/comma-style': ['error', 'last'],
    'stylistic/comma-spacing': ['error', { after: true }],
    'stylistic/brace-style': ['error', '1tbs', { allowSingleLine: true }],
    'stylistic/object-curly-spacing': ['error', 'always', { arraysInObjects: true, objectsInObjects: true }],
    'stylistic/object-curly-newline': ['error', { multiline: true, consistent: true }],
    'stylistic/object-property-newline': ['error', { allowAllPropertiesOnSameLine: true }],
    'stylistic/array-bracket-spacing': ['error', 'never'],
    'stylistic/array-bracket-newline': ['error', 'consistent'],
    'stylistic/array-element-newline': ['error', 'consistent'],
    'stylistic/space-before-function-paren': ['error', { anonymous: 'never', named: 'never', asyncArrow: 'always' }],
    'stylistic/space-before-blocks': ['error', 'always'],
    'stylistic/space-in-parens': ['error', 'never'],
    'stylistic/space-infix-ops': ['error', { int32Hint: false }],
    'stylistic/space-unary-ops': ['error', { words: true, nonwords: false }],
    'stylistic/keyword-spacing': ['error', { before: true, after: true }],
    'stylistic/key-spacing': ['error', { beforeColon: false, afterColon: true, mode: 'strict' }],
    'stylistic/semi-spacing': ['error', { before: false, after: true }],
    'stylistic/no-trailing-spaces': 'error',
    'stylistic/no-multi-spaces': 'error',
    'stylistic/no-tabs': 'error',
    'stylistic/eol-last': ['error', 'always'],
    'stylistic/no-multiple-empty-lines': ['error', { max: 2 }],
    'stylistic/max-len': ['error', { code: 120, ignoreUrls: true, ignoreRegExpLiterals: true, ignorePattern: 'class=' }],
    'stylistic/linebreak-style': ['error', 'unix'],
    'stylistic/spaced-comment': ['error', 'always', { block: { exceptions: ['*'] } }],
    'stylistic/arrow-spacing': 'error',
    'stylistic/arrow-parens': ['error', 'always'],
    'stylistic/no-floating-decimal': 'error',
    'stylistic/new-parens': 'error',
    'stylistic/switch-colon-spacing': ['error', { after: true, before: false }],
    'stylistic/template-curly-spacing': ['error', 'never'],
    'stylistic/rest-spread-spacing': ['error', 'never'],
    'stylistic/jsx-quotes': ['error', 'prefer-double'],
    'stylistic/padding-line-between-statements': [
        'error',
        { blankLine: 'always', prev: ['const', 'let', 'var', 'expression'], next: 'return' },
        { blankLine: 'always', prev: ['const', 'let', 'var', 'expression'], next: 'if' },
        { blankLine: 'always', prev: 'if', next: ['const', 'let', 'var'] },
        { blankLine: 'always', prev: 'expression', next: ['const', 'let', 'var'] },
        { blankLine: 'always', prev: 'multiline-block-like', next: '*' },
        { blankLine: 'always', prev: '*', next: 'multiline-block-like' },
    ],

    /* ==================== Core Rules ==================== */

    'no-await-in-loop': 'error',
    'no-console': 'warn',
    'no-template-curly-in-string': 'error',
    'no-unreachable-loop': 'error',
    'no-unsafe-optional-chaining': 'error',
    'require-atomic-updates': 'error',
    'array-callback-return': 'error',
    'block-scoped-var': 'error',
    'default-case': 'error',
    'default-case-last': 'error',
    'dot-notation': 'error',
    eqeqeq: ['error', 'always', { null: 'ignore' }],
    'no-alert': 'error',
    'no-caller': 'error',
    'no-constructor-return': 'error',
    'no-div-regex': 'error',
    'no-else-return': 'error',
    'no-eval': 'error',
    'no-extend-native': 'error',
    'no-extra-bind': 'error',
    'no-implicit-globals': 'error',
    'no-implied-eval': 'error',
    'no-iterator': 'error',
    'no-labels': 'error',
    'no-loop-func': 'error',
    'no-new': 'error',
    'no-new-func': 'error',
    'no-new-wrappers': 'error',
    'no-proto': 'error',
    'no-return-assign': 'error',
    'no-script-url': 'error',
    'no-self-compare': 'error',
    'no-sequences': 'error',
    'no-throw-literal': 'error',
    'no-unused-expressions': 'error',
    'no-useless-concat': 'error',
    'no-useless-return': 'error',
    'no-var': 'error',
    'prefer-const': ['error', { destructuring: 'any', ignoreReadBeforeAssign: false }],
    'prefer-exponentiation-operator': 'error',
    'prefer-object-spread': 'error',
    'prefer-rest-params': 'error',
    'prefer-spread': 'error',
    'prefer-template': 'error',
    'object-shorthand': ['error', 'always'],
    'no-nested-ternary': 'error',
    'no-unneeded-ternary': 'error',
    'one-var': ['error', 'never'],
    camelcase: ['error', { properties: 'never', ignoreDestructuring: true }],

    /* Off / Relaxed */
    'no-eq-null': 'off',
    radix: 'off',
    'require-await': 'warn',
    'no-continue': 'off',
    'no-shadow': 'off',
    'no-mixed-operators': 'off',
};
